namespace Pscp.Transpiler;

internal sealed partial class CSharpEmitter
{
    partial void EmitRuntimeHelpers()
    {
        _writer.WriteLine("public static class __PscpArray");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("public static T[] zero<T>(int n) => new T[n];");
        _writer.WriteLine("public static T[] fillNew<T>(int n) where T : new()");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("T[] result = new T[n];");
        _writer.WriteLine("for (int i = 0; i < n; i++) result[i] = new T();");
        _writer.WriteLine("return result;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static T[][] jagged<T>(int n, int m)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("T[][] result = new T[n][];");
        _writer.WriteLine("for (int i = 0; i < n; i++) result[i] = new T[m];");
        _writer.WriteLine("return result;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine();
        _writer.WriteLine();

        _writer.WriteLine("public static class __PscpSeq");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("public static T[] arrayOf<T>(params T[] items) => items;");
        _writer.WriteLine("public static IEnumerable<T> one<T>(T value) => new[] { value };");
        _writer.WriteLine("public static IEnumerable<T> concat<T>(params IEnumerable<T>[] sequences) => sequences.SelectMany(sequence => sequence);");
        _writer.WriteLine("public static T[] toArray<T>(IEnumerable<T> sequence) => sequence as T[] ?? sequence.ToArray();");
        _writer.WriteLine("public static List<T> toList<T>(IEnumerable<T> sequence) => sequence.ToList();");
        _writer.WriteLine("public static LinkedList<T> toLinkedList<T>(IEnumerable<T> sequence) => new(sequence);");
        _writer.WriteLine("public static T expr<T>(Func<T> func) => func();");
        _writer.WriteLine("public static int compare<T>(T left, T right) => Comparer<T>.Default.Compare(left, right);");
        _writer.WriteLine("public static IEnumerable<int> rangeInt(int start, int end, bool inclusive) => rangeInt(start, end, start <= end ? 1 : -1, inclusive);");
        _writer.WriteLine("public static IEnumerable<int> rangeInt(int start, int end, int step, bool inclusive)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("if (step == 0) throw new InvalidOperationException(\"Range step cannot be zero.\");");
        _writer.WriteLine("if (step > 0)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("for (int i = start; inclusive ? i <= end : i < end; i += step) yield return i;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("else");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("for (int i = start; inclusive ? i >= end : i > end; i += step) yield return i;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static IEnumerable<long> rangeLong(long start, long end, bool inclusive) => rangeLong(start, end, start <= end ? 1L : -1L, inclusive);");
        _writer.WriteLine("public static IEnumerable<long> rangeLong(long start, long end, long step, bool inclusive)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("if (step == 0) throw new InvalidOperationException(\"Range step cannot be zero.\");");
        _writer.WriteLine("if (step > 0)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("for (long i = start; inclusive ? i <= end : i < end; i += step) yield return i;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("else");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("for (long i = start; inclusive ? i >= end : i > end; i += step) yield return i;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static TResult[] map<T, TResult>(this IEnumerable<T> source, Func<T, TResult> selector) => source.Select(selector).ToArray();");
        _writer.WriteLine("public static T[] filter<T>(this IEnumerable<T> source, Func<T, bool> predicate) => source.Where(predicate).ToArray();");
        _writer.WriteLine("public static TState fold<T, TState>(this IEnumerable<T> source, TState seed, Func<TState, T, TState> folder)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("TState state = seed;");
        _writer.WriteLine("foreach (T item in source) state = folder(state, item);");
        _writer.WriteLine("return state;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static TState[] scan<T, TState>(this IEnumerable<T> source, TState seed, Func<TState, T, TState> folder)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("List<TState> values = new();");
        _writer.WriteLine("TState state = seed;");
        _writer.WriteLine("foreach (T item in source) { state = folder(state, item); values.Add(state); }");
        _writer.WriteLine("return values.ToArray();");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static (TResult[] mapped, TState state) mapFold<T, TResult, TState>(this IEnumerable<T> source, TState seed, Func<TState, T, (TResult mapped, TState state)> folder)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("List<TResult> values = new();");
        _writer.WriteLine("TState state = seed;");
        _writer.WriteLine("foreach (T item in source) { (TResult mapped, TState next) = folder(state, item); values.Add(mapped); state = next; }");
        _writer.WriteLine("return (values.ToArray(), state);");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static T sum<T>(this IEnumerable<T> source) where T : System.Numerics.INumber<T>");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("T total = T.Zero;");
        _writer.WriteLine("foreach (T item in source) total += item;");
        _writer.WriteLine("return total;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static TResult sumBy<T, TResult>(this IEnumerable<T> source, Func<T, TResult> selector) where TResult : System.Numerics.INumber<TResult>");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("TResult total = TResult.Zero;");
        _writer.WriteLine("foreach (T item in source) total += selector(item);");
        _writer.WriteLine("return total;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static T min<T>(T left, T right) => Comparer<T>.Default.Compare(left, right) <= 0 ? left : right;");
        _writer.WriteLine("public static T max<T>(T left, T right) => Comparer<T>.Default.Compare(left, right) >= 0 ? left : right;");
        _writer.WriteLine("public static T min<T>(this IEnumerable<T> source) => source.Min()!;");
        _writer.WriteLine("public static T max<T>(this IEnumerable<T> source) => source.Max()!;");
        _writer.WriteLine("public static T minBy<T, TKey>(this IEnumerable<T> source, Func<T, TKey> selector) => source.MinBy(selector)!;");
        _writer.WriteLine("public static T maxBy<T, TKey>(this IEnumerable<T> source, Func<T, TKey> selector) => source.MaxBy(selector)!;");
        _writer.WriteLine("public static int count<T>(this IEnumerable<T> source, Func<T, bool> predicate) => source.Count(predicate);");
        _writer.WriteLine("public static bool any<T>(this IEnumerable<T> source, Func<T, bool> predicate) => source.Any(predicate);");
        _writer.WriteLine("public static bool all<T>(this IEnumerable<T> source, Func<T, bool> predicate) => source.All(predicate);");
        _writer.WriteLine("public static T? find<T>(this IEnumerable<T> source, Func<T, bool> predicate) => source.FirstOrDefault(predicate);");
        _writer.WriteLine("public static int findIndex<T>(this IEnumerable<T> source, Func<T, bool> predicate)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("int index = 0;");
        _writer.WriteLine("foreach (T item in source) { if (predicate(item)) return index; index++; }");
        _writer.WriteLine("return -1;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static int findLastIndex<T>(this IEnumerable<T> source, Func<T, bool> predicate)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("int found = -1;");
        _writer.WriteLine("int index = 0;");
        _writer.WriteLine("foreach (T item in source) { if (predicate(item)) found = index; index++; }");
        _writer.WriteLine("return found;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static T[] sort<T>(this IEnumerable<T> source) => source.OrderBy(item => item).ToArray();");
        _writer.WriteLine("public static T[] sortBy<T, TKey>(this IEnumerable<T> source, Func<T, TKey> selector) => source.OrderBy(selector).ToArray();");
        _writer.WriteLine("public static T[] sortWith<T>(this IEnumerable<T> source, Func<T, T, int> comparer)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("List<T> list = source.ToList();");
        _writer.WriteLine("list.Sort((left, right) => comparer(left, right));");
        _writer.WriteLine("return list.ToArray();");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static T[] sortWith<T>(this IEnumerable<T> source, Comparison<T> comparer)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("List<T> list = source.ToList();");
        _writer.WriteLine("list.Sort(comparer);");
        _writer.WriteLine("return list.ToArray();");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static T[] sortWith<T>(this IEnumerable<T> source, IComparer<T> comparer)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("List<T> list = source.ToList();");
        _writer.WriteLine("list.Sort(comparer);");
        _writer.WriteLine("return list.ToArray();");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static bool chmin<T>(ref T target, T value)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("if (Comparer<T>.Default.Compare(value, target) < 0) { target = value; return true; }");
        _writer.WriteLine("return false;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static bool chmax<T>(ref T target, T value)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("if (Comparer<T>.Default.Compare(value, target) > 0) { target = value; return true; }");
        _writer.WriteLine("return false;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static T[] distinct<T>(this IEnumerable<T> source) => source.Distinct().ToArray();");
        _writer.WriteLine("public static T[] reverse<T>(this IEnumerable<T> source) => source.Reverse().ToArray();");
        _writer.WriteLine("public static T[] copy<T>(this IEnumerable<T> source) => source.ToArray();");
        _writer.WriteLine("public static Dictionary<T, int> groupCount<T>(this IEnumerable<T> source) where T : notnull");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("Dictionary<T, int> result = new();");
        _writer.WriteLine("foreach (T item in source) result[item] = result.TryGetValue(item, out int count) ? count + 1 : 1;");
        _writer.WriteLine("return result;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("public static Dictionary<T, int> freq<T>(this IEnumerable<T> source) where T : notnull => source.groupCount();");
        _writer.WriteLine("public static Dictionary<T, int> index<T>(this IEnumerable<T> source) where T : notnull");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("Dictionary<T, int> result = new();");
        _writer.WriteLine("int index = 0;");
        _writer.WriteLine("foreach (T item in source) { if (!result.ContainsKey(item)) result[item] = index; index++; }");
        _writer.WriteLine("return result;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine();

        _writer.WriteLine("public sealed class __PscpStdin");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("private readonly Queue<string> _tokens = new();");
        _writer.WriteLine("public T read<T>() => ConvertToken<T>(NextToken());");
        _writer.WriteLine("public int @int() => read<int>();");
        _writer.WriteLine("public long @long() => read<long>();");
        _writer.WriteLine("public double @double() => read<double>();");
        _writer.WriteLine("public decimal @decimal() => read<decimal>();");
        _writer.WriteLine("public bool @bool() => read<bool>();");
        _writer.WriteLine("public char @char() => read<char>();");
        _writer.WriteLine("public string str() => NextToken();");
        _writer.WriteLine("public string line() => Console.ReadLine() ?? string.Empty;");
        _writer.WriteLine("public string[] lines(int n) => Enumerable.Range(0, n).Select(_ => line()).ToArray();");
        _writer.WriteLine("public string[] words() => line().Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);");
        _writer.WriteLine("public char[] chars() => line().ToCharArray();");
        _writer.WriteLine("public T[] array<T>(int n) => Enumerable.Range(0, n).Select(_ => read<T>()).ToArray();");
        _writer.WriteLine("public List<T> list<T>(int n) => array<T>(n).ToList();");
        _writer.WriteLine("public LinkedList<T> linkedList<T>(int n) => new(array<T>(n));");
        _writer.WriteLine("public (T1, T2) tuple2<T1, T2>() => (read<T1>(), read<T2>());");
        _writer.WriteLine("public (T1, T2, T3) tuple3<T1, T2, T3>() => (read<T1>(), read<T2>(), read<T3>());");
        _writer.WriteLine("public (T1, T2)[] tuples2<T1, T2>(int n) => Enumerable.Range(0, n).Select(_ => tuple2<T1, T2>()).ToArray();");
        _writer.WriteLine("public (T1, T2, T3)[] tuples3<T1, T2, T3>(int n) => Enumerable.Range(0, n).Select(_ => tuple3<T1, T2, T3>()).ToArray();");
        _writer.WriteLine("public T[][] nestedArray<T>(int n, int m) => Enumerable.Range(0, n).Select(_ => array<T>(m)).ToArray();");
        _writer.WriteLine("public int[][] gridInt(int n, int m) => nestedArray<int>(n, m);");
        _writer.WriteLine("public long[][] gridLong(int n, int m) => nestedArray<long>(n, m);");
        _writer.WriteLine("public char[][] charGrid(int n) => Enumerable.Range(0, n).Select(_ => line().ToCharArray()).ToArray();");
        _writer.WriteLine("public string[][] wordGrid(int n) => Enumerable.Range(0, n).Select(_ => words()).ToArray();");
        _writer.WriteLine("private string NextToken()");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("while (_tokens.Count == 0)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("string? line = Console.ReadLine();");
        _writer.WriteLine("if (line is null) throw new EndOfStreamException(\"Unexpected end of input.\");");
        _writer.WriteLine("foreach (string token in line.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries)) _tokens.Enqueue(token);");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("return _tokens.Dequeue();");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("private static T ConvertToken<T>(string token)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("if (typeof(T) == typeof(string)) return (T)(object)token;");
        _writer.WriteLine("if (typeof(T) == typeof(int)) return (T)(object)int.Parse(token, CultureInfo.InvariantCulture);");
        _writer.WriteLine("if (typeof(T) == typeof(long)) return (T)(object)long.Parse(token, CultureInfo.InvariantCulture);");
        _writer.WriteLine("if (typeof(T) == typeof(double)) return (T)(object)double.Parse(token, CultureInfo.InvariantCulture);");
        _writer.WriteLine("if (typeof(T) == typeof(decimal)) return (T)(object)decimal.Parse(token, CultureInfo.InvariantCulture);");
        _writer.WriteLine("if (typeof(T) == typeof(bool)) return (T)(object)bool.Parse(token);");
        _writer.WriteLine("if (typeof(T) == typeof(char)) return (T)(object)token[0];");
        _writer.WriteLine("return (T)Convert.ChangeType(token, typeof(T), CultureInfo.InvariantCulture)!;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine();

        _writer.WriteLine("public sealed class __PscpStdout");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("private readonly TextWriter _writer = Console.Out;");
        _writer.WriteLine("public void write<T>(T value) => _writer.Write(__PscpRender.format(value));");
        _writer.WriteLine("public void writeln<T>(T value) => _writer.WriteLine(__PscpRender.format(value));");
        _writer.WriteLine("public void flush() => _writer.Flush();");
        _writer.WriteLine("public void lines<T>(IEnumerable<T> values) { foreach (T value in values) writeln(value); }");
        _writer.WriteLine("public void grid<T>(IEnumerable<IEnumerable<T>> grid) { foreach (IEnumerable<T> row in grid) writeln(__PscpRender.format(row)); }");
        _writer.WriteLine("public void join<T>(string separator, IEnumerable<T> values) => _writer.Write(string.Join(separator, values.Select(__PscpRender.format)));");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine();

        _writer.WriteLine("public static class __PscpRender");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("public static string format<T>(T value) => format((object?)value);");
        _writer.WriteLine("public static string format(object? value)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("if (value is null) return string.Empty;");
        _writer.WriteLine("if (value is string text) return text;");
        _writer.WriteLine("if (value is System.Runtime.CompilerServices.ITuple tuple)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("List<string> parts = new();");
        _writer.WriteLine("for (int i = 0; i < tuple.Length; i++) parts.Add(format(tuple[i]));");
        _writer.WriteLine("return string.Join(\" \", parts);");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("if (value is System.Collections.IEnumerable enumerable && value is not string)");
        _writer.WriteLine("{");
        _writer.Indent();
        _writer.WriteLine("List<string> parts = new();");
        _writer.WriteLine("foreach (object? item in enumerable) parts.Add(format(item));");
        _writer.WriteLine("return string.Join(\" \", parts);");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("return Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty;");
        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.Unindent();
        _writer.WriteLine("}");
    }
}





